name: Publish release to Maven
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build
        env:
          RELEASE: true

      - name: Publish to Maven
        run: ./gradlew publish
        env:
          RELEASE: true
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
