# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: Publish Snapshot to Maven
on:
  [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Publish to Maven (master)
        if: ${{ ${GITHUB_REF##*/} == 'master' }}
        run: ./gradlew publish
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

      - name: Publish to Maven (other-branch)
        if: ${{ GITHUB_REF##*/ != 'master' }}
        run: ./gradlew publish
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          RELEASE: true # mark as release to drop -SNAPSHOT
          VERSION_POSTFIX: ${{ GITHUB_REF##*/ }}